### ISSUE TITLE
Pixels of the unknown region

### ISSUE THREAD

**Issue by ghost** [atilimcetin/global-matting#1]
Hello,

Thank you for sharing the implementation.

In this [file](https://github.com/atilimcetin/global-matting/blob/master/globalmatting.cpp) I do not see where and how you did find the coordinates of the pixels of the unknown region ? I can not see that in any of your functions.

Regards,
BEGUERADJ

**Comment by atilimcetin** [comment]
The pixels of unknown regions are where the mask value is 128. You can search for 'trimap(y, x) == 128'

**Comment by ghost** [comment]
@atilimcetin Thank you very much.

**Comment by atilimcetin** [comment]
You're welcome.
